@BASE_URL = http://localhost:3000/api

###

GET  http://localhost:3000

###

GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/me

###
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
    "name" : "ugur",
    "surname" : "orken",
    "email" : "ugur@mail.com",
    "password" : "ugurPsw"
}
###

POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email" : "ugur@mail.com",
    "password" : "ugurPsw"
}


###

PATCH  {{BASE_URL}}/users/620c9914dd61004db861f84a
Content-Type: application/json

{
    "password":"22"
}
###

PATCH  {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjBlMWZmMjBmMjZlMmZmZTAyZDAxMTQiLCJlbWFpbCI6InVndXJAbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjQ1MTcyMzI4LCJleHAiOjE2NDUxNzU5Mjh9.aJgqLGpC286BtwvVkgIXvC3SUPh16jEREUUF4IFCw7Y

{
    "email" : "ipekNew@mail.com",
    "password" : "ipekNewPsw"
}

###
DELETE {{BASE_URL}}/users/620b4e76f8ff4a021b72d3fa
Content-Type: application/json

