@BASE_URL = http://localhost:3000/api

###

GET  http://localhost:3000

###

GET {{BASE_URL}}/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxZmNmOGRhYjlkMGMyNGFiYmYwOTciLCJlbWFpbCI6ImlwZWtAbWFpbC5jb20iLCJpYXQiOjE2NDY3MzQxOTksImV4cCI6MTY0NjczNzc5OX0.aOhlnjkaO8pUsf1AJiqxjYHQyQ83LjZG5bI0ZJ4yhLw

###
GET {{BASE_URL}}/users/userInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjEzNzZmODQ5ODVmYzczMWYxMGM1ZWEiLCJlbWFpbCI6ImRlbmVtZTFAbWFpbC5jb20iLCJpYXQiOjE2NDU0NDI4ODIsImV4cCI6MTY0NTQ0NjQ4Mn0.AaLgtbIjtxQQCqKxrXx_laAl776CHz1DJ4oVqML-hWA

###
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
    "name" : "Ecem",
    "surname" : "Balta",
    "email" : "balta@mail.com",
    "password" : "baltaPsw"
}
###
POST {{BASE_URL}}/groups/addGroup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIwYjJlMTI0MmFhMTVlMmUxZjM4MjMiLCJlbWFpbCI6ImFzZEBtYWlsLmNvbSIsImlhdCI6MTY0NjcyMTY5MSwiZXhwIjoxNjQ2NzI1MjkxfQ.pgOm2Vedx4SqlGZSz-V385f-FqYZq3t50XHis_K33FU

{
    "name" : "group chat deneme",
    "members" : ["6227056f542404afd3fea6ca","62270587542404afd3fea6cc"]
}
###

POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email" : "ipek@mail.com",
    "password" : "ipekPsw"
}


###

PATCH  {{BASE_URL}}/users/620c9914dd61004db861f84a
Content-Type: application/json

{
    "password":"22"
}
###

PATCH  {{BASE_URL}}/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjEzNzZmODQ5ODVmYzczMWYxMGM1ZWEiLCJlbWFpbCI6ImRlbmVtZUBtYWlsLmNvbSIsImlhdCI6MTY0NTQ0MjgyNSwiZXhwIjoxNjQ1NDQ2NDI1fQ.4KTdPtUAoS-vN1Cq2JJN2qwIA4R8sYku0PzaormZrVE

{
    "name" : "deneme1",
    "surname" : "deneme1",
    "email" : "deneme1@mail.com",
    "password" : "deneme1Psw"
}

###
DELETE {{BASE_URL}}/users/620b4e76f8ff4a021b72d3fa
Content-Type: application/json

###

GET {{BASE_URL}}/users/deleteAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjBmOTdkYzE2M2ZlYWE5MmMzMzIyNmYiLCJlbWFpbCI6InVndXIyQG1haWwuY29tIiwiaWF0IjoxNjQ1NDI0ODI0LCJleHAiOjE2NDU0Mjg0MjR9.W_2jVjpEszHSe5yOLYTKT5eiTTVpVDwICKz66JXNq_U

