@BASE_URL = http://localhost:3000/api

###

GET  http://localhost:3000

###

GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/3

###
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
    "name" : "user1",
    "surname" : "hash",
    "email" : "pswhash@mail.com",
    "password" : "3453453456"
}
###

POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email" : "ipek@mail.com",
    "password" : "1995"
}


###
PATCH  {{BASE_URL}}/users/620c9914dd61004db861f84a
Content-Type: application/json

{
    "password":"22"
}

###
DELETE {{BASE_URL}}/users/620b4e76f8ff4a021b72d3fa
Content-Type: application/json

